{% set name = "viewable" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/viewable-{{ version }}.tar.gz
  sha256: 95e84d6fd6287a980a8370d7ce23df341e347cc3741fa73c1a11509fa77e9d3b

build:
  entry_points:
    - viewable = viewable.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tkutil

test:
  imports:
    - viewable
  commands:
    - pip check
    - xvfb-run --auto-servernum bash -c 'viewable' &  # [unix]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/viewable
  summary: Python library to implement a GUI view with lifecycle
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
